name: generate snake animation

on:
  # Executa 1x por dia
  schedule:
    - cron: "0 0 * * *"
  # Permite rodar manualmente
  workflow_dispatch:
  # Executa quando houver push na branch principal
  push:
    branches:
      - main  # altere para 'master' se for o nome da sua branch principal

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Gera a animação da cobrinha 🐍
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: grad-valdeney
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Publica o SVG na branch "output"
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
